apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  INVENTORY_DB_USER: cG9zdGdyZXM=
  INVENTORY_DB_PASSWORD: cG9zdGdyZXMxMjM=
  INVENTORY_DB_NAME: aW52ZW50b3J5ZGI=
  ORDER_DB_USER: dXNlcg==
  ORDER_DB_PASSWORD: cGFzc3dvcmQ=
  ORDER_DB_NAME: b3JkZXJEQg==
