
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  GIT_USERNAME: YWJoYXlwYW5kZXljZGFj
  GIT_PASSWORD: Z2l0aHViX3BhdF8xMUFNSk9ZQ0kwSlFZNXY1NWNBclBIXzF1U3hMeVRJSUlORUx0TUdrM2JNelBjem4wT3llVjdrd3RIRE1tZXJmbHNQVkRMUE41S2Y3NFF0WkRX
  INVENTORY_DB_USER: cG9zdGdyZXM=
  INVENTORY_DB_PASSWORD: cG9zdGdyZXMxMjM=
  INVENTORY_DB_NAME: aW52ZW50b3J5ZGI=
  ORDER_DB_USER: dXNlcg==
  ORDER_DB_PASSWORD: cGFzc3dvcmQ=
  ORDER_DB_NAME: b3JkZXJEQg==
